### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by Iansus**
CurrentPlanet => current_planet

### CODE REVIEW

**Comment by Razican** [comment]
Please, do not change tabular indentation to spaces, change it back and I'll merge :)

**Comment by Iansus** [comment]
I'll change it back later.
Many other fixes coming ;)

**Comment by Iansus** [comment]
Spaces changed back to tabs
- Fixed shipyard not working
- Fixed research timer not displaying
- Minor PHP errors displaying

**Comment by Razican** [comment]
Great job! do you want it to get it merged now or do you have more commits coming?

**Comment by Iansus** [comment]
I did not see any more bug for now.
I think you can merge :)

## 

Jean MARSAULT
Consultant at Solucom

2015-06-14 14:50 GMT+02:00 Iban Eguia notifications@github.com:

**Comment by Razican** [comment]
Perfect, thanks!

**Pull request merged**
